// Agents run inside tmux sessions on a private socket (`tmux -L vatra`),
// so they survive server restarts and you can `tmux -L vatra attach -t vatra-<id>`.
import { execFile } from 'node:child_process';
import { rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

const TMUX_CONF = `# Generated by Vatra — overwritten on every server start.
set -g status off
set -g escape-time 0
set -g history-limit 50000
set -g remain-on-exit on
set -g mouse on
set -g focus-events on
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g window-size latest
setw -g aggressive-resize on
set -g destroy-unattached off
set -g exit-empty off
`;

export interface PaneState {
  exists: boolean;
  dead: boolean;
  exitCode: number | null;
  pid: number | null;
}

/** Env for tmux/claude processes: no nesting marker, no API credentials. */
export function cleanEnv(extra: Record<string, string> = {}): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = { ...process.env, ...extra };
  delete env.TMUX;
  delete env.TMUX_PANE;
  delete env.ANTHROPIC_API_KEY;
  delete env.ANTHROPIC_AUTH_TOKEN;
  delete env.IS_DEMO;
  delete env.CLAUDECODE;
  delete env.CLAUDE_CODE_ENTRYPOINT;
  // launchd/systemd start us without a locale; tmux then replaces non-ASCII with "_"
  const loc = env.LC_ALL || env.LC_CTYPE || env.LANG || '';
  if (!/utf-?8/i.test(loc)) {
    delete env.LC_ALL;
    env.LC_CTYPE = process.platform === 'darwin' ? 'en_US.UTF-8' : 'C.UTF-8';
    if (!env.LANG) env.LANG = env.LC_CTYPE;
  }
  return env;
}

export class Tmux {
  constructor(
    readonly socket: string,
    readonly confFile: string,
  ) {}

  static sessionName(taskId: number): string {
    return `vatra-${taskId}`;
  }

  writeConf(): void {
    writeFileSync(this.confFile, TMUX_CONF);
  }

  /** argv for spawning a tmux client (used by node-pty). */
  baseArgs(): string[] {
    return ['-u', '-L', this.socket, '-f', this.confFile];
  }

  run(args: string[], okCodes = [0]): Promise<{ stdout: string; stderr: string; code: number }> {
    return new Promise((resolve, reject) => {
      execFile('tmux', [...this.baseArgs(), ...args], { env: cleanEnv(), timeout: 10_000 }, (err, stdout, stderr) => {
        const raw = err ? (err as unknown as { code?: unknown }).code : 0;
        const code = typeof raw === 'number' ? raw : -1;
        if (!err || okCodes.includes(code)) resolve({ stdout: String(stdout), stderr: String(stderr), code });
        else reject(new Error(`tmux ${args.join(' ')}: ${String(stderr).trim() || err.message}`));
      });
    });
  }

  async version(): Promise<string | null> {
    return new Promise((resolve) => {
      execFile('tmux', ['-V'], (err, stdout) => resolve(err ? null : String(stdout).trim()));
    });
  }

  /** Reload config into an already running server (after an upgrade). */
  async reloadConf(): Promise<void> {
    await this.run(['source-file', this.confFile], [0, 1]);
  }

  async listSessions(): Promise<string[]> {
    // exit 1 = no server running yet
    const r = await this.run(['list-sessions', '-F', '#{session_name}'], [0, 1]);
    return r.code === 0 ? r.stdout.split('\n').filter(Boolean) : [];
  }

  /** Dead/alive state of every session's first pane, in one tmux call. */
  async allPanes(): Promise<Map<string, { dead: boolean; exitCode: number | null }>> {
    const r = await this.run(['list-panes', '-a', '-F', '#{session_name} #{pane_dead} #{pane_dead_status}'], [0, 1]);
    const out = new Map<string, { dead: boolean; exitCode: number | null }>();
    if (r.code !== 0) return out;
    for (const line of r.stdout.split('\n').filter(Boolean)) {
      const [name, dead, status] = line.split(' ');
      if (!out.has(name)) out.set(name, { dead: dead === '1', exitCode: dead === '1' && status ? Number(status) : null });
    }
    return out;
  }

  async pane(name: string): Promise<PaneState> {
    const r = await this.run(['list-panes', '-t', `=${name}`, '-F', '#{pane_dead} #{pane_dead_status} #{pane_pid}'], [0, 1]);
    if (r.code !== 0) return { exists: false, dead: true, exitCode: null, pid: null };
    const [dead, status, pid] = r.stdout.trim().split('\n')[0].split(' ');
    return {
      exists: true,
      dead: dead === '1',
      exitCode: dead === '1' && status !== '' ? Number(status) : null,
      pid: pid ? Number(pid) : null,
    };
  }

  async newSession(opts: { name: string; cwd: string; command: string[]; env?: Record<string, string>; cols?: number; rows?: number }): Promise<number | null> {
    await this.run([
      'new-session',
      '-d',
      '-s',
      opts.name,
      '-c',
      opts.cwd,
      '-x',
      String(opts.cols ?? 200),
      '-y',
      String(opts.rows ?? 50),
      ...opts.command,
    ]);
    return (await this.pane(opts.name)).pid;
  }

  /** Runs `shellCmd` (via /bin/sh, inside tmux) when the pane's process exits. */
  async onPaneDied(name: string, shellCmd: string): Promise<void> {
    await this.run(['set-hook', '-t', `=${name}:`, 'pane-died', `run-shell -b ${tmuxQuote(shellCmd)}`]);
  }

  /** Renames a session; used to migrate sessions started by older versions (ld-<id>). */
  async renameSession(from: string, to: string): Promise<boolean> {
    const r = await this.run(['rename-session', '-t', `=${from}`, to], [0, 1]);
    return r.code === 0;
  }

  async clearPaneDied(name: string): Promise<void> {
    await this.run(['set-hook', '-u', '-t', `=${name}:`, 'pane-died'], [0, 1]);
  }

  /** Appends everything the pane prints to `file`. */
  async pipeToFile(name: string, file: string): Promise<void> {
    await this.run(['pipe-pane', '-o', '-t', `=${name}:`, `cat >> ${shQuote(file)}`]);
  }

  /**
   * Puts text into the agent's prompt and presses Enter.
   * Short single-line text is typed (slash commands and `!bash` need real keystrokes);
   * long or multi-line text goes in as a bracketed paste so newlines don't submit early.
   */
  async sendText(name: string, text: string, tmpDir: string): Promise<void> {
    const t = text.replace(/\r\n?/g, '\n').replace(/\s+$/, '');
    const target = `=${name}:`;
    if (!t.includes('\n') && t.length <= 400) {
      await this.run(['send-keys', '-t', target, '-l', t]);
      await sleep(120 + Math.min(400, t.length * 2));
    } else {
      const file = join(tmpDir, `paste-${process.pid}-${Date.now()}.txt`);
      writeFileSync(file, t);
      const buf = `vatra-${Date.now()}`;
      try {
        await this.run(['load-buffer', '-b', buf, file]);
        await this.run(['paste-buffer', '-p', '-d', '-b', buf, '-t', target]);
      } finally {
        rmSync(file, { force: true });
      }
      await sleep(350 + Math.min(1200, t.length / 20));
    }
    await this.run(['send-keys', '-t', target, 'Enter']);
  }

  /** Sends named keys (tmux key names: Enter, Escape, Up, Down, BTab, C-c, 1…). */
  async sendKeys(name: string, keys: string[], delayMs = 60): Promise<void> {
    for (const k of keys) {
      await this.run(['send-keys', '-t', `=${name}:`, k]);
      await sleep(delayMs);
    }
  }

  /** Types text as-is (no Enter). */
  async typeLiteral(name: string, text: string): Promise<void> {
    await this.run(['send-keys', '-t', `=${name}:`, '-l', text]);
    await sleep(150 + Math.min(400, text.length * 2));
  }

  /** The visible screen of the pane as plain text. */
  async capture(name: string): Promise<string> {
    const r = await this.run(['capture-pane', '-p', '-t', `=${name}:`], [0, 1]);
    return r.code === 0 ? r.stdout : '';
  }

  async kill(name: string): Promise<void> {
    await this.run(['kill-session', '-t', `=${name}`], [0, 1]);
  }

  /** SIGTERM the pane process, SIGKILL after `graceMs`, then remove the session. */
  async stop(name: string, graceMs = 5000): Promise<void> {
    const p = await this.pane(name);
    if (!p.exists) return;
    if (!p.dead && p.pid) {
      try {
        process.kill(p.pid, 'SIGTERM');
      } catch {
        /* already gone */
      }
      const until = Date.now() + graceMs;
      while (Date.now() < until) {
        await new Promise((r) => setTimeout(r, 200));
        if ((await this.pane(name)).dead) break;
      }
      const after = await this.pane(name);
      if (after.exists && !after.dead && after.pid) {
        try {
          process.kill(after.pid, 'SIGKILL');
        } catch {
          /* gone */
        }
      }
    }
    await this.kill(name);
  }
}

/** POSIX single-quote escaping. */
export function shQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/** Quote for a tmux command-string argument. */
function tmuxQuote(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
}
